@startuml implement

hide empty members
' skinparam linetype ortho

' package plantumlgenerator.visitor {
    abstract class "<size:14>PlantUmlVisitor\n<size:10>plantumlgenerator.visitor" as PlantUmlVisitor
    class "<size:14>PlantUmlGenerator\n<size:10>plantumlgenerator.visitor" as  PlantUmlGenerator {
        +getCode(): String
    }
' }

' package padl.visitor{
    interface "<size:14>IGenerator\n<size:10>padl.visitor" as IGenerator {
        getCode(): String
    }
    interface "<size:14>IVisitor\n<size:10>padl.visitor" as IVisitor
' }

PlantUmlGenerator ..^ IGenerator
PlantUmlGenerator --^ PlantUmlVisitor

IGenerator --^ IVisitor

@enduml