@startuml test

hide empty members
skinparam linetype ortho

package java {
    package io {
        class Serializable {

        }
    }
    package lang {
        class Object {

        }
    }
}
package padl {
    package event {

        class AnalysisEvent {

        }

        class ElementEvent {

        }

        class EntityEvent {

        }

        class EventGenerator {

        }

        interface IEvent {

        }

        interface IModelListener {

        }

        interface IMotifModelListener {

        }

        class IdentificationEvent {

        }

        class InvokeEvent {

        }
    }
    package visitor {
        class IWalker {

        }
    }
}


AnalysisEvent ..^ IEvent

ElementEvent ..^ IEvent

EntityEvent ..^ IEvent

EventGenerator ..^ IWalker

EventGenerator ..^ Serializable


IMotifModelListener ^-- IModelListener


IdentificationEvent ..^ IEvent

InvokeEvent ..^ IEvent

@enduml